[theme]
base = "light"
backgroundColor = "#F8F8FA"
secondaryBackgroundColor = "#FFFFFF"
primaryColor = "#01A0FF"
textColor = "#333333"

[browser]
gatherUsageStats = false

[server]
port = 8501
headless = true
